/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Character {
    _id?: string;
    name?: string;
    films?: string[];
    shortFilms?: string[];
    tvShows?: string[];
    videoGames?: string[];
    parkAttractions?: string[];
    allies?: string[];
    enemies?: string[];
    imageUrl?: string;
    createdAt?: string;
    updatedAt?: string;
}
