/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as DisneyOpensource from "../index.js";

export interface CharacterList {
    totalPages?: number;
    nextPage?: string;
    previousPage?: string;
    data?: DisneyOpensource.Character[];
}
