/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {}
 */
export interface GetAllCharactersRequest {
    /**
     * Page number of results
     */
    page?: number;
    /**
     * Search for a character by name
     */
    name?: string;
}
