/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const DisneyOpensourceEnvironment = {
    Default: "https://api.disneyapi.dev",
} as const;

export type DisneyOpensourceEnvironment = typeof DisneyOpensourceEnvironment.Default;
